version: '3'
services:
  user-service:
    build: ../Koleso-user-service
    ports:
      - '3000:3000'

  auth-service:
    build: ../Koleso-auth-service
    ports:
      - '3001:3000'

  product-service:
    build: ../Koleso-product-service
    ports:
      - '3002:3000'

  cart-service:
    build: ../Koleso-cart-service
    ports:
      - '3003:3000'

  order-service:
    build: ../Koleso-order-service
    ports:
      - '3004:3000'

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - '5432:5432'
